name: Update Site
run-name: Update Site
on:
  schedule:
   # Run every 15 minutes
    - cron: '*/15 * * * *'
   # - cron:  '0 0 * * *'  # this means the action will run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Pull changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull origin main

    - name: Run script
      run: python main.py  

    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "Site update"
        git push
