name: Update Site

on:
  schedule:
   # - cron: '*/5 * * * *'  # Runs every 5 minutes
    - cron:  '0 0 * * *'  # this means the action will run daily at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace '3.x' with the version of Python you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace this with your actual dependencies

    - name: Run script
      run: python main.py  # Replace this with your actual Python script

    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Site update"
        git push
